ALTER TABLE TBL_DOCUMENTS ADD COLUMN nfieldvisible      NUMBER NULL;
ALTER TABLE TBL_DOCUMENTS ADD COLUMN nfieldhasdefaulval NUMBER   NULL;
ALTER TABLE TBL_DOCUMENTS ADD COLUMN sdefaultvalue      VARCHAR2(200) NULL;