CREATE TABLE TBL_MARKER_SERVICE(
 	 scode    VARCHAR2(30)       NOT NULL
	,screater VARCHAR2(100)      NULL
	,sdeleter VARCHAR2(100)      NULL
	,supdater VARCHAR2(100)      NULL
	,dcreate  DATETIME           NOT NULL DEFAULT NOW()
	,ddelete  DATETIME           NULL
	,dupdate  DATETIME           NULL
	,snamefield VARCHAR2(100)    NOT NULL
	,smarker  VARCHAR2(100)      NOT NULL
	,sconfiguration VARCHAR2(30) NULL
	,sservice  VARCHAR2(100)      NOT NULL
);
ALTER TABLE TBL_MARKER_SERVICE ADD CONSTRAINT KY_MS_PRIMARY PRIMARY KEY (scode);
ALTER TABLE TBL_MARKER_SERVICE ADD CONSTRAINT KY_MS_FOREIGN FOREIGN KEY (sconfiguration) REFERENCES TBL_CONFIGURATION(scode)