CREATE TABLE TBL_ACCOUNTING_ACCOUNT(
 	 scode    VARCHAR2(30)        NOT NULL
	,screater VARCHAR2(100)       NULL
	,sdeleter VARCHAR2(100)       NULL
	,supdater VARCHAR2(100)       NULL
	,dcreate  DATETIME            NOT NULL DEFAULT NOW()
	,ddelete  DATETIME            NULL
	,dupdate  DATETIME            NULL
	,sname    VARCHAR2(50)        NOT NULL
	,scodeaccount VARCHAR2(30)    NULL
	,sassociated  VARCHAR2(30)    NULL
	,senterprise  VARCHAR2(30)    NOT NULL
	,splantype    VARCHAR2(30)    NULL
	,stype        VARCHAR2(30)    NOT NULL
	,snature      VARCHAR2(30)    NULL
);
ALTER TABLE TBL_ACCOUNTING_ACCOUNT ADD PRIMARY KEY (scode);
ALTER TABLE TBL_ACCOUNTING_ACCOUNT ADD FOREIGN KEY (senterprise) REFERENCES TBL_ENTERPRISE(scode);
ALTER TABLE TBL_ACCOUNTING_ACCOUNT ADD FOREIGN KEY (sassociated) REFERENCES TBL_PARAMETER(scode);
ALTER TABLE TBL_ACCOUNTING_ACCOUNT ADD FOREIGN KEY (scodeaccount) REFERENCES TBL_PARAMETER(scode);
ALTER TABLE TBL_ACCOUNTING_ACCOUNT ADD FOREIGN KEY (splantype) REFERENCES TBL_PARAMETER(scode);
ALTER TABLE TBL_ACCOUNTING_ACCOUNT ADD FOREIGN KEY (stype) REFERENCES TBL_PARAMETER(scode);
ALTER TABLE TBL_ACCOUNTING_ACCOUNT ADD FOREIGN KEY (snature) REFERENCES TBL_PARAMETER(scode);