CREATE TABLE TBL_DETGENERATEQUOTE(
 	 scode    VARCHAR2(30)        NOT NULL
	,screater VARCHAR2(100)       NULL
	,sdeleter VARCHAR2(100)       NULL
	,supdater VARCHAR2(100)       NULL
	,dcreate  DATETIME            NOT NULL DEFAULT NOW()
	,ddelete  DATETIME            NULL
	,dupdate  DATETIME            NULL
	,spaymentreminder VARCHAR2(30) NOT NULL
	,squote   VARCHAR2(30)          NOT NULL
	,nneto    NUMBER                NOT NULL
	,ntax     NUMBER                NOT NULL
);
ALTER TABLE TBL_DETGENERATEQUOTE ADD CONSTRAINT KY_DGQ_PRIMARY PRIMARY KEY (scode);
ALTER TABLE TBL_DETGENERATEQUOTE ADD CONSTRAINT FK_DGQ_PR_FOREING FOREIGN KEY (spaymentreminder) REFERENCES TBL_PAYMENT_REMINDER(scode);
ALTER TABLE TBL_DETGENERATEQUOTE ADD CONSTRAINT FK_DGQ_Q_FOREING FOREIGN KEY (squote) REFERENCES TBL_QUOTE(scode);