CREATE TABLE TBL_ENTRY (
 	 scode    VARCHAR2(30)       NOT NULL
	,screater VARCHAR2(100)      NULL
	,sdeleter VARCHAR2(100)      NULL
	,supdater VARCHAR2(100)      NULL
	,dcreate  DATETIME           NOT NULL DEFAULT NOW()
	,ddelete  DATETIME           NULL
	,dupdate  DATETIME           NULL
	,sdriverin VARCHAR2(30)      NULL
	,sdriverout VARCHAR2(30)      NULL
	,sdescription VARCHAR2(200)      NULL
	,senterprise VARCHAR2(32)      NOT NULL
	,din      DATETIME             NOT NULL
	,dout     DATETIME             NULL
	,splate   VARCHAR2(8)          NULL
	,sowner   VARCHAR2(30)         NULL
	,sphonecontact VARCHAR2(15)    NULL
	,nstimatedtime NUMBER          NULL
	,nworktime     NUMBER          NULL
	,sworker   VARCHAR2(30)        NULL
);
ALTER TABLE TBL_ENTRY ADD CONSTRAINT KY_EY_PRIMARY PRIMARY KEY (scode);
ALTER TABLE TBL_ENTRY ADD CONSTRAINT KY_EY_WK_FOREING FOREIGN KEY (sworker) REFERENCES TBL_EMPLOYEE(scode);
ALTER TABLE TBL_ENTRY ADD CONSTRAINT KY_EY_EP_FOREING FOREIGN KEY (senterprise) REFERENCES TBL_ENTERPRISE(scode);
ALTER TABLE TBL_ENTRY ADD CONSTRAINT KY_EY_DI_FOREING FOREIGN KEY (sdriverin) REFERENCES TBL_PERSON(scode);
ALTER TABLE TBL_ENTRY ADD CONSTRAINT KY_EY_DO_FOREING FOREIGN KEY (sdriverout) REFERENCES TBL_PERSON(scode);
ALTER TABLE TBL_ENTRY ADD CONSTRAINT KY_EY_OW_FOREING FOREIGN KEY (sowner) REFERENCES TBL_PERSON(scode);
-- tabla intermedia entrada repuesto
CREATE TABLE TBL_ENTRY_REPLACEMENT (
 	 scode    VARCHAR2(30)       NOT NULL
	,screater VARCHAR2(100)      NULL
	,sdeleter VARCHAR2(100)      NULL
	,supdater VARCHAR2(100)      NULL
	,dcreate  DATETIME           NOT NULL DEFAULT NOW()
	,ddelete  DATETIME           NULL
	,dupdate  DATETIME           NULL
	,sentry   VARCHAR2(30)       NOT NULL
	,sreplacement VARCHAR2(30)   NOT NULL
);
ALTER TABLE TBL_ENTRY_REPLACEMENT ADD CONSTRAINT KY_ER_PRIMARY PRIMARY KEY (scode);
ALTER TABLE TBL_ENTRY_REPLACEMENT ADD CONSTRAINT KY_ER_EY_FOREING FOREIGN KEY (sentry) REFERENCES TBL_ENTRY(scode);
ALTER TABLE TBL_ENTRY_REPLACEMENT ADD CONSTRAINT KY_ER_RP_FOREING FOREIGN KEY (sreplacement) REFERENCES TBL_PRODUCT_SUMMARY(scode);
ALTER TABLE TBL_ENTRY_REPLACEMENT ADD CONSTRAINT KY_ER_EQ UNIQUE (sentry,sreplacement);
-- tabla intermedia entrada service
CREATE TABLE TBL_ENTRY_SERVICE(
 	 scode    VARCHAR2(30)       NOT NULL
	,screater VARCHAR2(100)      NULL
	,sdeleter VARCHAR2(100)      NULL
	,supdater VARCHAR2(100)      NULL
	,dcreate  DATETIME           NOT NULL DEFAULT NOW()
	,ddelete  DATETIME           NULL
	,dupdate  DATETIME           NULL
	,sentry   VARCHAR2(30)       NOT NULL
	,sservice VARCHAR2(30)       NOT NULL
);
ALTER TABLE TBL_ENTRY_SERVICE ADD CONSTRAINT KY_ES_PRIMARY PRIMARY KEY (scode);
ALTER TABLE TBL_ENTRY_SERVICE ADD CONSTRAINT KY_ES_EY_FOREING FOREIGN KEY (sentry) REFERENCES TBL_ENTRY(scode);
ALTER TABLE TBL_ENTRY_SERVICE ADD CONSTRAINT KY_ES_SV_FOREING FOREIGN KEY (sservice) REFERENCES TBL_SERVICE(scode);
ALTER TABLE TBL_ENTRY_SERVICE ADD CONSTRAINT KY_ES_UQ UNIQUE (sentry,sservice);
