ALTER TABLE TBL_CONFIG_GENERIC_FIELD ADD sgroup VARCHAR2(300) NULL;
ALTER TABLE TBL_CONFIG_GENERIC_FIELD ADD sfieldshow VARCHAR2(300) NULL;
ALTER TABLE TBL_CONFIG_GENERIC_FIELD ADD sdefault VARCHAR2(100) NULL;
ALTER TABLE TBL_CONFIG_GENERIC_FIELD ADD bvisible NUMBER NOT NULL DEFAULT 1 ;
