CREATE TABLE TBL_EMPLOYEE (
	 scode    VARCHAR2(30)       NOT NULL
	,screater VARCHAR2(100)      NULL
	,sdeleter VARCHAR2(100)      NULL
	,supdater VARCHAR2(100)      NULL
	,dcreate  DATETIME           NOT NULL DEFAULT NOW()
	,ddelete  DATETIME           NULL
	,dupdate  DATETIME           NULL
	,scentercost VARCHAR2(30)    NOT NULL
	,semail   VARCHAR2(150)      NULL
	,sstate   VARCHAR2(30)       NOT NULL
	,dentry   DATETIME           NOT NULL
	,dretirement DATETIME        NULL
	,sperson  VARCHAR2(30)       NOT NULL
	,spaytype VARCHAR2(30)       NOT NULL
);
ALTER TABLE TBL_EMPLOYEE ADD PRIMARY KEY (scode);
ALTER TABLE TBL_EMPLOYEE ADD FOREIGN KEY (scentercost) REFERENCES TBL_CENTER_COST(scode);
ALTER TABLE TBL_EMPLOYEE ADD FOREIGN KEY (sstate) REFERENCES TBL_PARAMETER(scode);
ALTER TABLE TBL_EMPLOYEE ADD FOREIGN KEY (sperson) REFERENCES TBL_PERSON(scode);
ALTER TABLE TBL_EMPLOYEE ADD FOREIGN KEY (spaytype) REFERENCES TBL_PARAMETER(scode);