CREATE TABLE TBL_PARAMETER_GROUP (
	 scode    VARCHAR2(30)       NOT NULL
	,screater VARCHAR2(100)      NULL
	,sdeleter VARCHAR2(100)      NULL
	,supdater VARCHAR2(100)      NULL
	,dcreate  DATETIME           NOT NULL DEFAULT NOW()
	,ddelete  DATETIME           NULL
	,dupdate  DATETIME           NULL
	,sgroup   VARCHAR2(30)        NOT NULL
	,sparameter VARCHAR2(30)     NOT NULL
);
ALTER TABLE TBL_PARAMETER_GROUP ADD PRIMARY KEY (scode);
ALTER TABLE TBL_PARAMETER_GROUP ADD UNIQUE (sgroup);
ALTER TABLE TBL_PARAMETER_GROUP ADD UNIQUE (sparameter);
ALTER TABLE TBL_PARAMETER_GROUP ADD FOREIGN KEY (sparameter) REFERENCES TBL_PARAMETER(scode);