CREATE TABLE TBL_PRODUCT_LOCATION (
	 scode    VARCHAR2(30)       NOT NULL
	,screater VARCHAR2(100)      NULL
	,sdeleter VARCHAR2(100)      NULL
	,supdater VARCHAR2(100)      NULL
	,dcreate  DATETIME           NOT NULL DEFAULT NOW()
	,ddelete  DATETIME           NULL
	,dupdate  DATETIME           NULL
	,ncantidad NUMBER            NOT NULL
	,sproduct VARCHAR2(30)       NOT NULL
	,slocation VARCHAR2(30)      NOT NULL
);
ALTER TABLE TBL_PRODUCT_LOCATION ADD PRIMARY KEY (scode);
ALTER TABLE TBL_PRODUCT_LOCATION ADD FOREIGN KEY (sproduct) REFERENCES TBL_PRODUCT (scode);
ALTER TABLE TBL_PRODUCT_LOCATION ADD FOREIGN KEY (slocation) REFERENCES TBL_LOCATION (scode);
ALTER TABLE TBL_PRODUCT_LOCATION ADD UNIQUE (sproduct,slocation);