ALTER TABLE TBL_ACCOUNTING_ACCOUNT DROP COLUMN scodeaccount;
ALTER TABLE TBL_ACCOUNTING_ACCOUNT ADD COLUMN scodeaccount VARCHAR2(30)    NULL;
ALTER TABLE TBL_ACCOUNTING_ACCOUNT DROP COLUMN sassociated;
ALTER TABLE TBL_ACCOUNTING_ACCOUNT ADD COLUMN sassociated VARCHAR2(30)    NULL;
ALTER TABLE TBL_ACCOUNTING_ACCOUNT ADD FOREIGN KEY (sassociated) REFERENCES TBL_ACCOUNTING_ACCOUNT(scode);
