CREATE TABLE TBL_CONCEPT(
 	 scode    VARCHAR2(30)        NOT NULL
	,screater VARCHAR2(100)       NULL
	,sdeleter VARCHAR2(100)       NULL
	,supdater VARCHAR2(100)       NULL
	,dcreate  DATETIME            NOT NULL DEFAULT NOW()
	,ddelete  DATETIME            NULL
	,dupdate  DATETIME            NULL
	,sexpenseaccount VARCHAR2(30) NOT NULL
	,sbilltopay  VARCHAR2(30)     NOT NULL
	,sdescription VARCHAR2(30)    NULL
	,senterprise VARCHAR2(30)     NOT NULL
	,sstate VARCHAR2(30)          NOT NULL
	,ssubconcept VARCHAR2(30)     NULL
	,sname    VARCHAR2(100)       NOT NULL
);
ALTER TABLE TBL_CONCEPT ADD CONSTRAINT KY_CT_PRIMARY PRIMARY KEY (scode);
ALTER TABLE TBL_CONCEPT ADD CONSTRAINT KY_CT_ST_FOREING FOREIGN KEY (sstate) REFERENCES TBL_PARAMETER(scode);
ALTER TABLE TBL_CONCEPT ADD CONSTRAINT KY_CT_EP_FOREING FOREIGN KEY (senterprise) REFERENCES TBL_ENTERPRISE(scode);
ALTER TABLE TBL_CONCEPT ADD CONSTRAINT KY_CT_EA_FOREING FOREIGN KEY (sexpenseaccount) REFERENCES TBL_ACCOUNTING_ACCOUNT(scode);
ALTER TABLE TBL_CONCEPT ADD CONSTRAINT KY_CT_BP_FOREING FOREIGN KEY (sbilltopay) REFERENCES TBL_ACCOUNTING_ACCOUNT(scode);